// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/documents": {
    params: {};
  };
  "/chat": {
    params: {};
  };
  "/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/documents" | "/chat" | "/settings";
  };
  "routes/dashboard/layout.tsx": {
    id: "routes/dashboard/layout";
    page: "/" | "/documents" | "/chat" | "/settings";
  };
  "routes/dashboard/overview.tsx": {
    id: "routes/dashboard/overview";
    page: "/";
  };
  "routes/dashboard/documents.tsx": {
    id: "routes/dashboard/documents";
    page: "/documents";
  };
  "routes/dashboard/chat.tsx": {
    id: "routes/dashboard/chat";
    page: "/chat";
  };
  "routes/dashboard/settings.tsx": {
    id: "routes/dashboard/settings";
    page: "/settings";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/dashboard/layout": typeof import("./app/routes/dashboard/layout.tsx");
  "routes/dashboard/overview": typeof import("./app/routes/dashboard/overview.tsx");
  "routes/dashboard/documents": typeof import("./app/routes/dashboard/documents.tsx");
  "routes/dashboard/chat": typeof import("./app/routes/dashboard/chat.tsx");
  "routes/dashboard/settings": typeof import("./app/routes/dashboard/settings.tsx");
};